sudo: required

services:
  - docker
  
language: bash
  
install: true
  
before_script:
  - chmod +x scripts/build.sh
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  
script:
  - scripts/build.sh

after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker tag tynor88/docker-resilio-sync-arm32v6 tynor88/docker-resilio-sync-arm32v6:latest
      docker push tynor88/docker-resilio-sync-arm32v6:latest
    fi
