sudo: required

services:
  - docker
  
install: true
  
before_install:
  - chmod +x scripts/run.sh

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
  - echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' | sudo tee -a /proc/sys/fs/binfmt_misc/register
  
script:
  - scripts/run.sh
