sudo: required

services:
  - docker
  
language: bash
  
install: true
  
before_install:
  - chmod +x scripts/run.sh

before_script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # get qemu-arm-static binary
  - mkdir tmp
  - >
    pushd tmp &&
    curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz &&
    tar xzf qemu-arm-static.tar.gz &&
    popd
  - sudo mv tmp/qemu-arm-static /usr/bin/qemu-arm-static
  
script:
  - scripts/run.sh
