sudo: required

services:
  - docker
  
language: bash
  
install: true
  
before_install:
  - chmod +x scripts/build.sh

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  
script:
  - scripts/build.sh
