sudo: required

services:
  - docker
  
install: true
  
before_install:
  - chmod +x scripts/run.sh

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  
script:
  - scripts/run.sh
